### ISSUE TITLE
Failing samples

### ISSUE THREAD

**Issue by markknol** [HeapsIO/heaps.io#10]
> 21 ERRORED : 
 [adjustColor/adjustColor_hl,adjustColor/adjustColor_js,adjustColor/adjustColor_swf,base3D/base3D_hl,base3D/base3D_js,base3D/base3D_swf,fullscreen/fullscreen_hl,fullscreen/fullscreen_js,fullscreen/fullscreen_swf,gpuParticles/gpuParticles_hl,gpuParticles/gpuParticles_js,gpuParticles/gpuParticles_swf,network/network_hl,network/network_js,network/network_swf,sao/sao_hl,sao/sao_js,sao/sao_swf,skin/skin_hl,skin/skin_js,skin/skin_swf]

Haxe 3.4.4
Heaps 1.1.0
In Travis

**Comment by ncannasse** [comment]
Fixed with https://github.com/HeapsIO/heaps/commit/0e3daeef1821da21c8030bbab95a085a3fd9023a
