### ISSUE TITLE
Game cover images should have same dimensions 

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps.io#11]
See showcases in about.html (available on designUpdate branch right now)

![image](https://user-images.githubusercontent.com/1671695/36176531-2f3aed04-1113-11e8-99d8-660eab553cbe.png)

**Comment by ncannasse** [comment]
@markknol can we force the coverage to a specific size in CSS for now ? If not, please update Northgard image so it fits the size.

**Comment by ibilon** [comment]
Was fixed by https://github.com/HeapsIO/heaps.io/commit/e2a844663810e31b522eeb3c4661ec316f491ca7.
