### ISSUE TITLE
Add a 4th web game to have a nice 2x2 grid :)

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps.io#14]
![image](https://user-images.githubusercontent.com/1671695/36176834-3957d1fc-1114-11e8-95b2-462a1b9da42e.png)

**Comment by markknol** [comment]
Just make one, Ill add it 😛

**Comment by deepnight** [comment]
Same as #17, I discovered the showcase.json file, I'll fix that by myself :)
