### ISSUE TITLE
Add android & ios logos

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps.io#18]

**Comment by markknol** [comment]
Hey looks bit odd here (Chrome 64.0.3282.167, Windows 10)
![image](https://user-images.githubusercontent.com/576184/36216286-9e267990-11ae-11e8-9ce3-5c6eebcd2b6c.png)

**Comment by deepnight** [comment]
Couldn't reproduce this one :/ Is it still happening on latest master version? I made a minor, probably unrelated fix, just in case.

**Comment by markknol** [comment]
Will check when Im on laptop again

**Comment by markknol** [comment]
Yep still happening on latest version
