### ISSUE TITLE
Automatic deployment

### ISSUE THREAD

**Issue by markknol** [HeapsIO/heaps.io#2]
* [x] Travis should be set up. It needs to `build-run-dox.hxml` then `heaps.io.hxml` then copy everything from `/output` to the _gh-pages_ branch.
* [x] We should come up with better flow for compiling examples straight from https://github.com/HeapsIO/heaps/tree/master/samples (At the moment that requires very specific libraries which cannot be expressed in specific Haxe/Haxelib versions)

**Comment by andyli** [comment]
Completed the first item. I will leave the others to you :)

**Comment by markknol** [comment]
Thank you so much! Will look into those soon!
