### ISSUE TITLE
Platform icons

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#22]
Platforms icons are messed up on current version, is it normal?
@markknol @deepnight 
![image](https://user-images.githubusercontent.com/1022912/39073052-c2427e0c-44ec-11e8-88d0-25a7789f3caa.png)

**Comment by markknol** [comment]
Duplicate of https://github.com/HeapsIO/heaps.io/issues/18

**Comment by markknol** [comment]
Its probably because that icon is png, while rest is svg
