### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#25]
Scenario 1 : Heaps/JS + VSCode
Scenario 2 : Heaps/HL + VSCode (SDL)

We need a complete tutorial with screenshots.

- download and install Haxe + Heaps
- get visual studio
- install language support (vshaxe pack)
- setup / compile / run

@markknol do you want to help here?

**Comment by BigPhilCombo** [comment]
I think this will be a good task for me as I need to get familiar with the engine myself.

**Comment by BigPhilCombo** [comment]
It seems like there's already a decent example here - https://github.com/HeapsIO/heaps.io/tree/master/assets/content/documentation/Getting-started

**Comment by ncannasse** [comment]
I rewrote a full getting started tutorial, which is now online.
