### ISSUE TITLE
heaps.io domain - not yet launched?

### ISSUE THREAD

**Issue by jcward** [HeapsIO/heaps.io#33]
As noted in the gitter, the site hosted on [heapsio.github.io/heaps.io](https://heapsio.github.io/heaps.io) seems to be up and running.

So why does the [heaps.io](http://heaps.io) still show "coming soon"? Is this intentional, or is the github site only a preview for now? Are there blocking issues for launch? Hosting, or SSL?

**Comment by ibilon** [comment]
Not sure if why but these pages don't have content
* https://heapsio.github.io/heaps.io/documentation/h2d/layers.html
* https://heapsio.github.io/heaps.io/documentation/h3d/multipass-explained.html
* https://heapsio.github.io/heaps.io/documentation/h3d/scene-and-camera.html
* https://heapsio.github.io/heaps.io/documentation/h2d/optimizing-bitmap-usage.html (some content but no explanation)

that would not be very professional to release it like that ;)

**Comment by ncannasse** [comment]
Yes, there's a lot of documentation TBD :'( Without Phil, I guess I have to get it done.
https://docs.google.com/document/d/1AXdDPww5YnCHsuegG3DCm9hr2jTyZlBsjCHUH8r-KTg/edit?usp=sharing

**Comment by markknol** [comment]
Website + domain is live 🎉
