### ISSUE TITLE
Samples text shows up as boxes (Chrome / Linux)

### ISSUE THREAD

**Issue by jcward** [HeapsIO/heaps.io#34]
In the samples section of the website, on Chrome 67 on Linux, the text for all samples does not properly render. :( I did check my Windows VM, and text did render properly:

![image](https://user-images.githubusercontent.com/2192439/42699121-0788b1e4-867d-11e8-9cd5-2fb12d90d814.png)

![image](https://user-images.githubusercontent.com/2192439/42699153-1a700212-867d-11e8-9869-f3068a4ba735.png)

**Comment by markknol** [comment]
Download Windows to solve this issue :)

**Comment by ncannasse** [comment]
That's interesting. It seems as if the transparency is disabled. I can't reproduce on Firefox on my Ubutu VM.

**Comment by jcward** [comment]
Ah ha, Firefox 45 on Ubuntu 14.04 is indeed working.

Maybe it' sjust Chrome... though I don't think I've had problems on shadertoy.com, kodegarden.org, or [webglsamples.org](http://webglsamples.org/aquarium/aquarium.html), though I'm not entirely sure what kind of webgl toy to look at:

![image](https://user-images.githubusercontent.com/2192439/42784870-bbbed7d2-890d-11e8-9d5e-ccd6cdc7ef51.png)

**Comment by ncannasse** [comment]
I would be interested if you can debug why this is happening. Maybe some issue with the way we cache state changes in h3d/impl/GlDriver.hx (setMaterialBits)

**Comment by jcward** [comment]
I tried (maybe?) disabling the curMatBats, but it had no effect:

```
  curMatBits = -1;
  if( curMatBits < 0 ) diff = -1;
```

Some more data, on my computer:

Chromium 65.0.3325.181 -- affected
Chrome 67.0.3396.87 -- affected
Firefox 45.0 -- not affected

Co-worker's Ubuntu 16.04 Chrome 65.0.3325.162 -- not affected 

I tried git checkout of heaps repo back to Nov 2016, and I still had the problem.

Interesting, another observation of the affected Chrome browsers: models are all red, but primitives render properly:

**Chrome vs Firefox:**
![image](https://user-images.githubusercontent.com/2192439/43741745-a864ebf6-998c-11e8-8619-b6c018f7aa47.png)

**Chrome: models==red vs primitives==ok:**
![image](https://user-images.githubusercontent.com/2192439/43741807-e0c38ea8-998c-11e8-94d3-2bc0a93951a8.png)

![interactive](https://user-images.githubusercontent.com/2192439/43784270-f16cb1b4-9a20-11e8-91f7-c7fe962d7ea3.gif)

**Comment by jcward** [comment]
Just clicked this from twitter -- same issue with deepnightfr's [blossom game](http://deepnight.net/games/blossom/) (which is heaps-based). Same problem with alpha in the bitmaps.

**Firefox:**
![image](https://user-images.githubusercontent.com/2192439/44062670-994b824a-9f1a-11e8-81d0-00cb90ef2dd4.png)


**Chrome:**
![image](https://user-images.githubusercontent.com/2192439/44096171-e479dd70-9f97-11e8-9bcc-53e93d9b9b80.png)

Again, I'm not sure if it's in the engine or my graphics driver / browser... but I don't see the problem in various web demos. Here's pixi.js [blendmodes demo](https://pixijs.io/examples/#/demos/blendmodes.js), which definitely has alpha sprites:

![image](https://user-images.githubusercontent.com/2192439/44096254-17e0bd50-9f98-11e8-8715-ed54af89271e.png)

**Comment by ncannasse** [comment]
Note: it does not seem to be related to bitmap decoding because in the
Sample2D screenshot the alpha on rotating Haxe logo is done by code.

**Comment by jcward** [comment]
Ah, fascinating, I'm starting to think this is a problem with my browser / gpu, and not heaps itself.

The above pixi blendmodes demo is running is a **software renderer** because they pass the context option `failIfMajorPerformanceCaveat : true`.

Looking at http://webglreport.com, it says my Chrome browser has "major performance caveat: yes". I can also see that my Firefox browser (which works), does not support webgl2, but only webgl:

![image](https://user-images.githubusercontent.com/2192439/44435744-96d00180-a56e-11e8-9620-59fce01c13d5.png)

I tried forcing heaps / `GlDriver.hx` to use webgl instead of webgl2, and in Chrome then the world demo is all white with other weird artifacts:

![image](https://user-images.githubusercontent.com/2192439/44435794-f0d0c700-a56e-11e8-8a41-803cfaf42e38.png)

**Comment by jcward** [comment]
Interesting, it's definitely browser / driver related. If I run Chrome with `--ignore-gpu-blacklist`, it runs Heaps content just fine (interestingly, in this mode it advertises as not supporting webgl2, only webgl.)

There are some interesting details in the GPU reports from `chrome://gpu` in each mode:

[chrome_gpu.pdf](https://github.com/HeapsIO/heaps.io/files/2319783/chrome_gpu.pdf)
[chrome_gpu_ignore_blacklist.pdf](https://github.com/HeapsIO/heaps.io/files/2319784/chrome_gpu_ignore_blacklist.pdf)

I suppose another possible issue to file is -- how to detect this to allow some kind of graceful error message.
