### ISSUE TITLE
Samples List

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#40]
- update PBR image with actual sample image
- remove FullScreen (not working in JS - HL only) 
- add new sample (Blur) + ignore new sample (ShaderAdvanced)

**Comment by ncannasse** [comment]
Also when you click on "Samples" section, the "Samples" menu item does not highlight

**Comment by markknol** [comment]
The samples menu-button now highlights

samples can be edited here: https://github.com/HeapsIO/heaps.io/edit/master/assets/content/samples/samples.json
sample images go here:
https://github.com/HeapsIO/heaps.io/tree/master/assets/includes/img/samples
