### ISSUE TITLE
Documentation navigation

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#47]
It would be nice at the bottom of a documentation page to have some way to navigate to the next section.
For instance at the bottom of this page 
https://heaps.io/documentation/hello-world.html
you would get links to prev / next sections "Installation" and "Hello HashLink"

**Comment by Doppp** [comment]
Currently, https://heaps.io/documentation/ leads to a `PAGE NOT FOUND` page.

**Comment by ncannasse** [comment]
@Doppp yes we're aware of the the issue, will fix it asap

**Comment by ncannasse** [comment]
Regarding navigation, we might want to list the subsections at the end of each "root page", for instance
https://heaps.io/documentation/getting-started.html
