### ISSUE TITLE
Samples keyboard

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#48]
Samples who needs keyboard does no seem to work , see https://heaps.io/samples/input.html for example.
maybe they can't be focused ?

**Comment by markknol** [comment]
Do you request focus from heaps?
This might be needed because samples run in iframe.

Otherwise the sample could be updated, where it says "tap for focus" if canvas is blurred, or something

**Comment by ncannasse** [comment]
I don't request focus, Heaps by default add listeners to the document body, but yes the iframe might be triggering some problem. Why the iframe btw ? :)

**Comment by markknol** [comment]
Ill try without iframe
