### ISSUE TITLE
Heaps version

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#52]
There seems to be various places where Heaps version is set:

In https://github.com/HeapsIO/heaps.io/blob/master/src/BuildSamples.hx#L14
In https://github.com/HeapsIO/heaps.io/blob/master/build-run-dox.hxml
In https://github.com/HeapsIO/heaps.io/blob/master/run-dox.hxml
Some other place? (it seems latest heaps.io is not up to date with Heaps 1.5.0 ?)

Maybe having a single /version.txt that tells which heaps version to use for all commands would help?

**Comment by markknol** [comment]
I don't want to spend time creating something that generates the hxml that uses version.txt, since it is easy to just update these 3 files.
