### ISSUE TITLE
New Showcase games not visible.

### ISSUE THREAD

**Issue by hristo-kanchev** [HeapsIO/heaps.io#70]
Description:

I saw that @ncannasse pushed out a couple of months ago a commit where he adds Dune: Spice Wars and Wartales to the Steam Showcase located under https://heaps.io/about.html but currently they are not visible.

Is the CI/CD pipeline broken?

**Comment by ncannasse** [comment]
Yes and I have no time to look into it 😅

Le sam. 23 mars 2024 à 21:53, Hristo Kanchev ***@***.***> a
écrit :

**Comment by hristo-kanchev** [comment]
Whomever has access to https://travis-ci.org/HeapsIO/heaps.io can you share the logs? I'd love to help, but I don't have access rights. Cheers!
