### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#9]
We want to complete the Heaps.io Showcase page with two sections:

on top:
- steam games (Dead Cells, Northgard, Evoland, etc.)

under:
- web games (LudumDare etc.)

Can we have a simple-to-edit .json with URL + thumbmail image + title / author that would generate the page ?  We also want it more compact, having the information on rollover since there will be 

I need to recompile my old LudumDare games with Heaps/JS output as it's become very hard to play Flash content in browser. 

We don't need all games, just some visual variety and links to play / sourcecode for learning.

**Comment by deepnight** [comment]
Something like this :)
https://motion-twin.com/fr/games#lab

**Comment by markknol** [comment]
Is there a list of webgames that I can include already?

**Comment by markknol** [comment]
I made list of games populated by a json file.
https://github.com/HeapsIO/heaps.io/blob/master/assets/content/showcase/showcase.json

**Comment by deepnight** [comment]
Added supported platforms & source code URL to json.
@ncannasse You should check if all platforms for shiro games are correct, not sure about console versions of Evoland 1 & 2 :)

**Comment by ncannasse** [comment]
Please remove consoles versions for evoland. NG is not yet released on OSX/Linux but will be upon final release so we can keep them here.

**Comment by ncannasse** [comment]
But you can add iOS/Android versions for evoland 1 ;)

**Comment by ncannasse** [comment]
I have updated the file

**Comment by ncannasse** [comment]
(not sure "android" and "ios" are correctly handled)

**Comment by deepnight** [comment]
Fixed!

**Comment by markknol** [comment]
Nothing to be done here anymore 👍
